### ISSUE TITLE
Transaction with op_return out not worked

### ISSUE THREAD

**Issue by jrazer** [pebwindkraft/trx_cl_suite#39]
Not sign and not propertly decoded

**Comment by pebwindkraft** [comment]
Hi, currently on a longer trip in West-Africa. though I haven't prepared anything for OP_RETURN, I'd be curious to know, how you structured the tx. It must be assembled manually to sign. Re decoding: I could easily add required things...

**Comment by pebwindkraft** [comment]
There are a set of OP_Return tx in testcase 19 of "./tcls_tc_tx2txt.sh". If jRazer's example still shows error, need to get the raw tx to do further analysis. Hence I close the issue here.
