### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by tcqq** [pebwindkraft/trx_cl_suite#42]
Hello, can you leave your contact information? I have a question about bitcoin, I want to ask you.

**Comment by pebwindkraft** [comment]
Maybe this is not the right forum to contact me for bitcoin related questions. They are better posed into forums like "bitcoin.stackexchange.com" or "bitcointalk.org". Anyhow, as you are asking: you may want to send a question to pebwindkraft@gmail.com. I don't look at these mails regularly, though. I'll lock this thread.

**Comment by tcqq** [comment]
@pebwindkraft Hello, I have sent the question to your email via Gmail, thank you for your reply.

**Comment by tcqq** [comment]
@pebwindkraft Hi, have you received the email I sent?

**Comment by pebwindkraft** [comment]
yup, replied on 25th of Nov to "Alan Dreamer" <usertcqq@gmail.com>
